### ISSUE TITLE
Dependencies cannot be accessed

### ISSUE THREAD

**Issue by morangeous** [decaf-project/Droidscope#4]
Hello! I am really interested in this repo, but I can't download the dependecies successfully via
`wget https://cluster.hpcc.ucr.edu/~zqi020/file_for_unpack/external.tar.gz`
`wget https://cluster.hpcc.ucr.edu/~zqi020/file_for_unpack/images.tar.gz`
`wget https://cluster.hpcc.ucr.edu/~zqi020/file_for_unpack/prebuilts.tar.gz`
`wget https://cluster.hpcc.ucr.edu/~zqi020/file_for_unpack/out.tar.gz`
so is this link available now? 
Any help will be appreciate! Forward to your reply!

**Comment by enlighten5** [comment]
Hi,
The server is under a maintenance shutdown today for 24 hours. Please try these links later:)

**Comment by morangeous** [comment]
oh, I see, thanks for your reply
